[package]
name = "ttt"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Vitiuk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rand = "0.3.14"
three-d = "0.14.1"
